/**:
  ros__parameters:
    lidar_odometry:
      lidar_min_range: 3.0
      lidar_max_range: 80.0
      keyframe_voxel_size: 0.25
    output_frame_parent: "/odom"
    output_frame_child: "/base_scan"