/**:
  ros__parameters:
    lidar_odometry:
      lidar_min_range: 4.0
      lidar_max_range: 80.0
      keyframe_voxel_size: 0.2
      keyframe_matching_voxel_size: 0.3
      keyframe_update_voxel_size: 0.1
      keyframe_cleanup_range: 80.0
    output_frame_parent: "/odom"
    output_frame_child: "/base_scan"
    publish_full_keyframe: false